### ISSUE TITLE
Controllers must use Pickup rather than Jump

### ISSUE THREAD

**Issue by fjb751115** [tfraudet/Reason-ArturiaKeylabEssential-Remote#10]
Hi Thierry

Thank you for the amazing work you have done to control Reason. Is there a way to set the controllers to use "Pickup" rather than "Jump"? I noted with Mackie control this can be set. Is there a way to not have the faders jump using your config. When you move between instruments the controller forces last used position to the new instance.

**Comment by tfraudet** [comment]
Hi @fjb751115 thx for your feedback. Did you try to modify de 'Daw Fader mode' parameter in the Arturia Midi control center app ? does it change something ?
![Screenshot 2021-10-19 at 21 40 23](https://user-images.githubusercontent.com/34861241/137979321-1850e662-3f52-4a75-939f-cf7d6c1a61cc.png)
 
Also please test with this modify version of the codec that send faders value to the controller when a new instrument is selected in Reason
[Keylab61 Essential.zip](https://github.com/tfraudet/Reason-ArturiaKeylabEssential-Remote/files/7376408/Keylab61.Essential.zip)
.

**Comment by tfraudet** [comment]
Hi,

I only have the version 11 so far.
On this version, there is no edit mode on the combinator so I don't know
what it is possible to do on v12.

Cordialement
Thierry Fraudet.

**Comment by fjb751115** [comment]
Hi Thierry

I have tested but it still jumps, but no worries, I am using it like that now. Everything else works great

Thank you very much

**Comment by tfraudet** [comment]
Ok, have fun with your gears :-)
